import { useState } from 'react';
import { View } from 'react-native';
import { T, Art, Pic, Panel, Tap, Button, Header, Screen, IconButton, WeekStrip, useFrame, s } from './components';
import { colors } from '../../src/nutrisole/extensions/model';
import ProgressRing from '../../src/nutrisole/ProgressRing.native';
import type { CoreProps } from './CoreScreens';
import TaskLinks from './TaskLinks';
const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
export default function WeeklyPlan({ back, open, store, go }: CoreProps) {
  const { compact, width, fontScale } = useFrame();
  const gutter = 12;
  const [day, setDay] = useState(0); const [tab, setTab] = useState<'Meals' | 'Nutrition'>('Meals'); const [weekOffset, setWeekOffset] = useState(0);
  const key = `${weekOffset}:${day}:breakfast`; const accepted = store.state.accepted.includes(key); const replacement = store.state.substitutes[key]; const feedback = store.state.feedback[key]; const firstDate = 18 + weekOffset * 7;
  function substitutes() { open({ title: 'Choose a substitute', description: 'Choose a meal for this day. These sample meals contain no tree nuts or shellfish.', choices: ['Berry Overnight Oats', 'Apple & Yogurt Bowl'].map(label => ({ label, selected: (replacement || 'Berry Overnight Oats') === label, action: () => store.update(old => ({ ...old, substitutes: { ...old.substitutes, [key]: label } })) })) }); }
  const mealCard = (breakfast: boolean) => <Panel style={{ padding: 14, gap: 10 }}>
    <View style={[s.row, { flexWrap: 'wrap', gap: 6 }]}><T size={21} bold style={{ flexGrow: 1 }}>{breakfast ? 'Breakfast' : 'Lunch'}</T><T size={13} color={colors.muted}>{breakfast ? '7:00 – 9:00 AM' : '12:00 – 2:00 PM'}</T></View>
    <Tap label={breakfast ? 'Breakfast details' : 'Lunch details'} onPress={() => open({ title: breakfast ? replacement || 'Berry Overnight Oats' : 'Grilled Chicken Quinoa Bowl', description: breakfast ? 'Seeded demo meal: 320 cal, 18 g protein, 42 g carbohydrate, 10 g fat.' : 'Chicken, quinoa, mixed greens, avocado. Seeded demo meal: 420 cal, 36 g protein, 48 g carbohydrate, 14 g fat.' })} style={[s.row, { alignItems: 'flex-start', gap: 13 }]}><Pic asset={breakfast ? replacement === 'Apple & Yogurt Bowl' ? 'apple-thumbnail' : 'berry-oats' : 'chicken-quinoa-bowl'} size={compact ? 70 : 82} radius={12} /><View style={[s.flex, { gap: 6 }]}><T size={17} bold>{breakfast ? replacement || 'Berry Overnight Oats' : 'Grilled Chicken Quinoa Bowl'}</T><T size={14} color={colors.muted}>{breakfast ? replacement === 'Apple & Yogurt Bowl' ? 'Apple, Greek yogurt, oats, chia seeds' : 'Oats, Greek yogurt, berries, chia seeds' : 'Chicken, quinoa, mixed greens, avocado'}</T><View style={[s.wrap, { gap: 8 }]}><T size={16}><T bold size={16}>{breakfast ? '320' : '420'}</T> cal</T><T size={14}>{breakfast ? '18g P' : '36g P'}</T><T size={14}>{breakfast ? '42g C' : '48g C'}</T><T size={14}>{breakfast ? '10g F' : '14g F'}</T></View></View></Tap>
    {breakfast && <><View style={[s.wrap, { gap: 8 }]}><Button label="Accept breakfast" text={accepted ? 'Accepted' : 'Accept'} art="weekly-accept" primary onPress={() => store.update(old => ({ ...old, accepted: old.accepted.includes(key) ? old.accepted.filter(k => k !== key) : [...old.accepted, key] }))} style={{ flexGrow: 1, flexBasis: 125, minWidth: 125, paddingHorizontal: 10, gap: 8 }} textSize={16} artSize={18} /><Button label="Substitute breakfast" text="Substitute" art="weekly-substitute" onPress={substitutes} style={{ flexGrow: 1, flexBasis: 125, minWidth: 125, paddingHorizontal: 10, gap: 8, borderWidth: 1, borderColor: '#d8dad6', backgroundColor: '#faf9f5' }} textSize={16} artSize={18} /><Button label="Breakfast options" icon="Ellipsis" onPress={() => open({ title: 'Breakfast', description: `${replacement || 'Berry Overnight Oats'} · 320 cal · 18g protein · 42g carbs · 10g fat`, choices: [{ label: 'Change this meal', action: substitutes }, { label: 'Restore suggested meal', action: () => store.update(old => ({ ...old, substitutes: { ...old.substitutes, [key]: 'Berry Overnight Oats' } })) }] })} style={{ minWidth: 44, paddingHorizontal: 10, borderWidth: 1, borderColor: '#d8dad6' }}><Art name="weekly-more" size={18} /></Button></View>
      <Tap label="Meal feedback" onPress={() => open({ title: 'Tell us what you prefer', fields: [{ key: 'feedback', label: 'Feedback', value: feedback || '', multiline: true }], save: v => { if (!v.feedback?.trim()) return 'Write a short preference before saving.'; store.update(old => ({ ...old, feedback: { ...old.feedback, [key]: v.feedback.trim() } })); } })} style={[s.row, { padding: 13, backgroundColor: '#f8f7f3', borderWidth: .8, borderColor: '#e5e4df', borderRadius: 10 }]}><Art name="weekly-feedback" size={18} /><T size={14} color="#82878a" style={s.flex}>{feedback || 'Not a fan? Tell us why...'}</T></Tap></>}
  </Panel>;
  return <Screen route="weekly-plan" gutter={gutter} paper="paper-weekly" header={<Header title="Weekly Plan" subtitle={`Mar ${firstDate} – Mar ${firstDate + 6}`} back={back} art="weekly-back" end={<IconButton label="Choose plan week" art="weekly-calendar" onPress={() => open({ title: 'Plan week', description: 'Choose a local demonstration week.', choices: [-1, 0, 1].map(offset => ({ label: `Mar ${18 + offset * 7} – Mar ${24 + offset * 7}`, selected: weekOffset === offset, action: () => setWeekOffset(offset) })) })} />} />}>
    <WeekStrip items={days.map((d, i) => <Tap key={d} label={`Select ${d}`} onPress={() => setDay(i)} style={{ minHeight: 51, paddingVertical: 8, paddingHorizontal: 2, justifyContent: 'center', gap: 5, backgroundColor: day === i ? colors.green : colors.card, borderRadius: 11 }}><T size={14} color={day === i ? '#fff' : colors.muted} style={s.center}>{d}</T><T size={14} color={day === i ? '#fff' : colors.muted} style={s.center}>{firstDate + i}</T></Tap>)} />
    <Panel style={[s.row, { flexWrap: 'wrap', gap: 0, paddingHorizontal: 8, minHeight: 80 }]}><View style={[s.flex, { minWidth: fontScale > 1.2 ? Math.min(width - 2 * gutter - 16, 112 * fontScale) : 0, gap: 4 }]}><T size={22} bold style={s.center}>1,650</T><T size={15} color={colors.muted} style={s.center}>cal goal</T></View>{fontScale <= 1.2 && <View style={{ width: .6, alignSelf: 'stretch', backgroundColor: colors.border }} />}<View style={[s.flex, { minWidth: fontScale > 1.2 ? Math.min(width - 2 * gutter - 16, 112 * fontScale) : 0, alignItems: 'center', gap: 4 }]}><View style={[s.row, { gap: 8, flexWrap: 'wrap', justifyContent: 'center' }]}>{accepted ? <ProgressRing size={42} stroke={6} fraction={1} /> : <Pic asset="weekly-progress-ring" size={42} radius={0} />}<View style={{ gap: 3 }}><T size={22} bold style={s.center}>{accepted ? '5/5' : '4/5'}</T><T size={15} color="#627176" style={s.center}>meals</T></View></View></View>{fontScale <= 1.2 && <View style={{ width: .6, alignSelf: 'stretch', backgroundColor: colors.border }} />}<View style={[s.flex, { minWidth: fontScale > 1.2 ? Math.min(width - 2 * gutter - 16, 112 * fontScale) : 0, gap: 4 }]}><T size={22} bold style={s.center}>{accepted ? '100%' : '82%'}</T><T size={15} color={colors.muted} style={s.center}>adherence</T></View></Panel>
    <Panel texture="gray-track-texture-tile" border={false} style={[s.row, { padding: 0, gap: 0 }]}>{(['Meals', 'Nutrition'] as const).map(t => <Tap key={t} label={`Show ${t.toLowerCase()}`} onPress={() => setTab(t)} style={{ flex: 1, paddingVertical: 14, borderBottomWidth: tab === t ? 4 : 0, borderColor: colors.green }}><T size={19} bold={tab === t} color={tab === t ? colors.green : colors.ink} style={s.center}>{t}</T></Tap>)}</Panel>
    {tab === 'Meals' ? <>{mealCard(true)}{mealCard(false)}</> : <Panel><T size={21} bold>Daily nutrition</T><T size={15} color={colors.muted}>{days[day]} {firstDate + day} · Seeded meal plan</T>{[['Calories', '1,650 kcal', '#ff9448'], ['Protein', '96 g', '#929bf2'], ['Carbohydrates', '184 g', '#59ccb9'], ['Fat', '58 g', '#fbd479']].map(([name, value, color]) => <View key={name} style={{ gap: 8, paddingVertical: 8 }}><View style={[s.row, { flexWrap: 'wrap', gap: 4 }]}><T size={17} style={s.flex}>{name}</T><T size={17} bold>{value}</T></View><View style={{ height: 7, borderRadius: 5, backgroundColor: color }} /></View>)}</Panel>}
    <TaskLinks route="weekly-plan" go={go} />
  </Screen>;
}
