"""Losslessly extract individual supplied icon artwork. No text or full UI captures."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import json, hashlib, re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / 'NutriSole-UI-Concepts'
ICONS = {
 'onboarding-recognition': ('01_21_15 AM-1', (102,1127,210,1236)),
 'onboarding-personalized': ('01_21_15 AM-1', (102,1285,210,1394)),
 'onboarding-support': ('01_21_15 AM-1', (102,1444,210,1553)),
 'onboarding-continue': ('01_21_15 AM-1', (649,1613,795,1755)),
 'home-scan-camera': ('01_21_16 AM-2', (119,766,288,934)),
 'home-plan-calendar': ('01_21_16 AM-2', (113,1015,167,1073)),
 'home-health-bars': ('01_21_16 AM-2', (489,1015,542,1073)),
 'home-plan-chevron': ('01_21_16 AM-2', (379,1087,396,1116)),
 'home-health-chevron': ('01_21_16 AM-2', (747,1087,765,1116)),
 'home-scan-chevron': ('01_21_16 AM-2', (736,833,758,868)),
 'home-see-all-chevron': ('01_21_16 AM-2', (750,1260,765,1284)),
 'home-nav-home': ('01_21_16 AM-2', (112,1649,156,1696)),
 'home-nav-plan': ('01_21_16 AM-2', (260,1650,301,1697)),
 'home-nav-health': ('01_21_16 AM-2', (560,1650,611,1699)),
 'home-nav-profile': ('01_21_16 AM-2', (710,1650,753,1699)),
 'home-nav-camera': ('01_21_16 AM-2', (353,1586,510,1739)),
 'scan-close': ('01_21_18 AM-3', (79,169,177,267)),
 'scan-flash': ('01_21_18 AM-3', (690,168,788,267)),
 'scan-confirmation': ('01_21_18 AM-3', (300,460,363,522)),
 'scan-instruction-target': ('01_21_18 AM-3', (241,1278,291,1331)),
 'scan-shutter': ('01_21_18 AM-3', (347,1442,513,1607)),
 'log-back': ('01_21_19 AM-4', (99,252,124,292)),
 'log-info': ('01_21_19 AM-4', (705,405,752,451)),
 'log-minus': ('01_21_19 AM-4', (91,887,169,965)),
 'log-plus': ('01_21_19 AM-4', (297,887,376,965)),
 'log-estimate-apple': ('01_21_19 AM-4', (115,1052,153,1094)),
 'weekly-back': ('01_21_21 AM-5', (94,285,130,320)),
 'weekly-calendar': ('01_21_21 AM-5', (717,281,764,329)),
 'weekly-accept': ('01_21_21 AM-5', (163,1149,201,1178)),
 'weekly-substitute': ('01_21_21 AM-5', (439,1148,475,1184)),
 'weekly-more': ('01_21_21 AM-5', (705,1157,740,1174)),
 'weekly-feedback': ('01_21_21 AM-5', (126,1252,164,1290)),
 'profile-back': ('01_21_23 AM-6', (89,291,116,331)),
 'profile-account-chevron': ('01_21_23 AM-6', (735,440,755,474)),
 'profile-dietary': ('01_21_23 AM-6', (102,586,143,628)),
 'profile-allergens': ('01_21_23 AM-6', (102,676,143,718)),
 'profile-activity': ('01_21_23 AM-6', (102,764,144,814)),
 'profile-mobility': ('01_21_23 AM-6', (103,858,144,905)),
 'profile-glucose': ('01_21_23 AM-6', (105,952,140,995)),
 'profile-timezone': ('01_21_23 AM-6', (102,1040,144,1082)),
 'profile-health': ('01_21_23 AM-6', (95,1154,163,1223)),
 'profile-connected': ('01_21_23 AM-6', (598,1175,620,1196)),
 'profile-privacy': ('01_21_23 AM-6', (105,1318,145,1363)),
 'profile-privacy-chevron': ('01_21_23 AM-6', (738,1325,757,1356)),
}
manifest = []
records = {}
sheet = Image.new('RGB', (800, ((len(ICONS)+7)//8)*140), '#f2f3ef')
draw = ImageDraw.Draw(sheet)
font = ImageFont.truetype('C:/Windows/Fonts/arial.ttf', 10)
for index,(name,(suffix,bounds)) in enumerate(ICONS.items()):
    path = next(SOURCE.glob(f'*{suffix}.png'))
    im = Image.open(path).crop(bounds)
    asset = 'icon-' + name
    for directory in [ROOT/'assets/source', ROOT/'public/nutrisole']:
        im.save(directory / f'{asset}.png')
    x,y,r,b = bounds
    records[name] = {'asset':asset, 'x':x, 'y':y, 'w':r-x, 'h':b-y}
    manifest.append({'id':asset,'source':str(path),'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'boundsLTRB':bounds,'operations':['crop only','lossless PNG encode'],'content':'One original icon, badge or unlabeled icon button. Background retained. No UI text, data, device chrome, or full-screen image.'})
    ox,oy=(index%8)*100,(index//8)*140
    thumb=im.copy();thumb.thumbnail((90,110))
    sheet.paste(thumb,(ox+5,oy))
    draw.text((ox+2,oy+112),name.replace('-','\n',1),font=font,fill='#183c2b')
(ROOT/'assets/source/icon-art.provenance.json').write_text(json.dumps(manifest,indent=2))
(ROOT/'src/nutrisole/sourceArt.ts').write_text('// Original individual icon crops; generated by scripts/extract-icon-art.py.\nexport const sourceArt = '+json.dumps(records,indent=2)+' as const;\nexport type SourceArtName = keyof typeof sourceArt;\n')
native_file = ROOT/'src/nutrisole/assets.native.ts'
native_text = re.sub(r'  // BEGIN SOURCE ICONS.*?  // END SOURCE ICONS\n', '', native_file.read_text(), flags=re.S)
native_entries = ''.join(f"  '{a['id']}': require('../../assets/source/{a['id']}.png'),\n" for a in manifest)
native_file.write_text(native_text.replace('};', '  // BEGIN SOURCE ICONS\n'+native_entries+'  // END SOURCE ICONS\n};'))
sheet.save(ROOT/'artifacts/qa/source-icon-art.png')
print(f'Extracted {len(manifest)} individual original icons and generated source coordinates.')
