// Embedded into use_figma with SCENES and STATE supplied from the local ledger.
const page=await figma.getNodeByIdAsync(STATE.pageId);
await figma.setCurrentPageAsync(page);
const created=[],mutated=[],images=[];
const keep=n=>{created.push(n.id);return n};
const fonts={NutriSans:{family:'Roboto',style:'Regular'},NutriSansBold:{family:'Roboto',style:'SemiBold'},NutriSerif:{family:'Libre Caslon Display',style:'Regular'},NutriSerifBold:{family:'Libre Caslon Text',style:'Bold'},NutriSerifText:{family:'Libre Caslon Text',style:'Regular'}};
await Promise.all(Object.values(fonts).map(f=>figma.loadFontAsync(f)));
const library=await figma.getNodeByIdAsync(STATE.libraryId);
if(library.children.length)throw new Error('Construction phase already exists; inspect ledger before retry');
// Adapted from the skill's createVariableCollection helper, single reference mode.
const collection=figma.variables.createVariableCollection('NutriSole / Reference');
collection.renameMode(collection.modes[0].modeId,'Reference');
const mode=collection.modes[0].modeId;
const variables={};
function rgb(hex){let v=hex.replace('#','');if(v.length===3)v=v.split('').map(x=>x+x).join('');return {r:parseInt(v.slice(0,2),16)/255,g:parseInt(v.slice(2,4),16)/255,b:parseInt(v.slice(4,6),16)/255};}
function token(name,value,type='COLOR',scopes=['FRAME_FILL','SHAPE_FILL','TEXT_FILL','STROKE_COLOR']){const v=figma.variables.createVariable(name,collection,type);v.scopes=scopes;v.setValueForMode(mode,type==='COLOR'?{...rgb(value),a:value.length===9?parseInt(value.slice(7),16)/255:1}:value);v.setVariableCodeSyntax('WEB','nutrisole.'+name.replaceAll('/','.'));variables[name]=v;return v;}
const colors={green:'#123f2c',black:'#080d16',muted:'#5c626d',border:'#ebe7df',cream:'#faf8f1',white:'#ffffff'};
for(const [k,v]of Object.entries(colors))token('color/'+k,v);
token('radius/card',18,'FLOAT',['CORNER_RADIUS']);token('radius/round',48,'FLOAT',['CORNER_RADIUS']);token('spacing/component',16,'FLOAT',['GAP']);
const styles={};
for(const [name,font]of Object.entries(fonts)){const t=figma.createTextStyle();t.name='NutriSole/'+name;t.fontName=font;t.fontSize=14;t.lineHeight={unit:'PIXELS',value:18};t.letterSpacing={unit:'PIXELS',value:-0.35};styles[name]=t;}
function paint(hex){const match=Object.entries(colors).find(([k,v])=>v===hex);let p={type:'SOLID',color:rgb(hex),opacity:hex.length===9?parseInt(hex.slice(7),16)/255:1};return match?figma.variables.setBoundVariableForPaint(p,'color',variables['color/'+match[0]]):p;}
function section(name){const f=keep(figma.createAutoLayout('HORIZONTAL'));f.name=name;f.resize(700,100);f.layoutWrap='WRAP';f.itemSpacing=16;f.counterAxisSpacing=16;f.fills=[];library.appendChild(f);f.layoutSizingHorizontal='FIXED';f.layoutSizingVertical='HUG';return f;}
const assetArea=section('Source assets · independent photos, paper, and icon artwork');
const masters={};
const assetNames=[...new Set(SCENES.flatMap(s=>s.nodes.flatMap(n=>[n.asset,n.texture].filter(Boolean))))];
for(const name of assetNames){const c=keep(figma.createComponent());c.name='Asset/'+name;c.description='Independent source content asset; never a flattened UI. Replace this image fill to update its instances.';c.resize(96,64);c.layoutMode='HORIZONTAL';c.fills=[];c.clipsContent=true;assetArea.appendChild(c);c.layoutSizingHorizontal='FIXED';c.layoutSizingVertical='FIXED';masters[name]=c;images.push({asset:name,nodeId:c.id,path:name.endsWith('-photo-masked')?'artifacts/figma/'+name+'.png':'assets/source/'+name+'.png'});}
const typeArea=section('Typography · live text');
const label=keep(figma.createComponent());label.name='Label';label.description='Live source text. Content exposed as a text property; the screen supplies typography overrides from Txt.';label.resize(320,48);label.layoutMode='VERTICAL';label.fills=[];label.clipsContent=false;typeArea.appendChild(label);label.layoutSizingHorizontal='FIXED';label.layoutSizingVertical='FIXED';
const baseText=keep(figma.createText());baseText.name='Text';baseText.fontName=fonts.NutriSans;baseText.fontSize=14;baseText.textAutoResize='HEIGHT';baseText.resize(320,18);baseText.characters='NutriSole';baseText.fills=[paint(colors.black)];label.appendChild(baseText);baseText.layoutSizingHorizontal='FILL';const labelKey=label.addComponentProperty('Content','TEXT','NutriSole');baseText.componentPropertyReferences={characters:labelKey};
const surfaceArea=section('Surfaces · reusable cards');
const surface=keep(figma.createComponent());surface.name='Surface';surface.description='Code Surface: independently editable fill, border, rounded corners, and sizing.';surface.resize(320,64);surface.layoutMode='VERTICAL';surface.clipsContent=true;surface.fills=[paint('#fffdf9')];surface.strokes=[paint(colors.border)];surface.strokeWeight=.9;surface.setBoundVariable('topLeftRadius',variables['radius/card']);surface.setBoundVariable('topRightRadius',variables['radius/card']);surface.setBoundVariable('bottomLeftRadius',variables['radius/card']);surface.setBoundVariable('bottomRightRadius',variables['radius/card']);surfaceArea.appendChild(surface);
const frames={};
for(const scene of SCENES){const frame=await figma.getNodeByIdAsync(STATE.frames[scene.route]);if(frame.children.length)throw new Error('Screen already populated: '+scene.route);frames[scene.route]=frame;frame.fills=[paint(scene.route==='scan'?'#111111':colors.cream)];frame.cornerRadius=42;mutated.push(frame.id);const [ox,oy,w,h]=scene.crop;const scale=Math.min(393/w,852/h),dx=(393-w*scale)/2;const content=keep(figma.createAutoLayout('VERTICAL'));content.name='Source coordinate canvas';content.resize(393,852);content.fills=[];content.clipsContent=false;frame.appendChild(content);
function place(n,p){content.appendChild(n);n.layoutPositioning='ABSOLUTE';n.x=dx+(p.x-ox)*scale;n.y=(p.y-oy)*scale;return n;}
function trackedInstance(c){const n=keep(c.createInstance());for(const ch of n.findAll(()=>true))created.push(ch.id);return n;}
for(const p of scene.nodes){if(p.kind==='text'){const fontAlias=p.style?.fontFamily||(p.serif?(p.bold?'NutriSerifBold':'NutriSerif'):(p.bold?'NutriSansBold':'NutriSans'));const inst=trackedInstance(label);inst.name=p.text.replaceAll('\n',' ').slice(0,65);inst.setProperties({[labelKey]:p.text});inst.resize(p.w*scale,Math.max(1,(p.line||p.fs*1.18)*scale*p.text.split('\n').length));const t=inst.findAllWithCriteria({types:['TEXT']})[0];t.textStyleId=styles[fontAlias].id;t.fontName=fonts[fontAlias];t.fontSize=(p.fs||36)*scale;t.lineHeight={unit:'PIXELS',value:(p.line||p.fs*1.18)*scale};t.letterSpacing={unit:'PIXELS',value:(p.style?.letterSpacing??-.7)*scale};t.textAlignHorizontal=(p.align||'left').toUpperCase();t.fills=[paint(p.color||colors.black)];t.textAutoResize='HEIGHT';t.resize(p.w*scale,t.height);t.layoutSizingHorizontal='FILL';if(p.runs?.length){let cursor=0;for(const run of p.runs){const start=p.text.indexOf(run.text,cursor);if(start>=0){t.setRangeFontName(start,start+run.text.length,fonts[run.style.fontFamily||fontAlias]);cursor=start+run.text.length;}}}place(inst,p);
// Figma has no affine glyph stretching. Avoid compressing Alex until glyphs overlap.
// Other calibrated headline advances use tracking; all glyphs stay editable.
const sx=p.style?.transform?.[0]?.scaleX??(p.serif&&p.bold?.valueOf()?0.82:1);if(sx!==1&&p.text.length>1){if(p.serif&&p.bold){t.fontSize=(p.fs||36)*scale*sx;}else{const natural=keep(figma.createText());natural.fontName=fonts[fontAlias];natural.fontSize=t.fontSize;natural.characters=p.text;natural.letterSpacing=t.letterSpacing;const advance=natural.width;const correction=advance*(1-sx)/(p.text.length-1);t.letterSpacing={unit:'PIXELS',value:t.letterSpacing.value-correction};natural.remove();created.pop();}}
}else if(['photo','art','scene'].includes(p.kind)){const n=trackedInstance(masters[p.asset]);n.name=p.kind==='art'?'Icon/'+p.name:'Photo/'+p.asset;n.resize(p.w*scale,p.h*scale);n.cornerRadius=(p.radius||0)*scale;place(n,p);
}else if(p.kind==='surface'){const n=trackedInstance(surface);n.name='Surface/'+(p.texture||p.fill||'paper');n.resize(p.w*scale,p.h*scale);n.cornerRadius=(p.radius??36)*scale;n.strokes=p.border===false?[]:[paint(colors.border)];n.strokeWeight=1.8*scale;n.fills=[paint(p.fill||'#fffdf9')];if(p.texture)n.fills=[];place(n,p);if(p.texture)images.push({asset:p.texture,nodeId:n.id,path:'assets/source/'+p.texture+'.png',existingMaster:masters[p.texture].id});
}else if(p.kind==='hit'){const n=keep(figma.createRectangle());n.name='Action/'+p.label;n.resize(p.w*scale,p.h*scale);n.fills=[];n.strokes=[];place(n,p);
}else if(p.kind==='divider'||p.kind==='box'){const n=keep(figma.createRectangle());n.name=p.kind==='divider'?'Divider':'Indicator';n.resize(p.w*scale,p.h*scale);n.cornerRadius=(p.style?.borderRadius||0)*scale;n.fills=[paint(p.color||p.style?.backgroundColor||colors.border)];n.opacity=p.style?.opacity??1;place(n,p);if(p.style?.transform?.[0]?.rotate){const deg=parseFloat(p.style.transform[0].rotate),angle=deg*Math.PI/180;n.x+=(p.w-p.w*Math.cos(angle)+p.h*Math.sin(angle))*scale/2;n.y+=(p.h-p.w*Math.sin(angle)-p.h*Math.cos(angle))*scale/2;n.rotation=-deg;}
}else if(p.kind==='camera-frame'){const svg='<svg xmlns="http://www.w3.org/2000/svg" width="781" height="1371" viewBox="41 37 781 1371"><g fill="none" stroke="#fff" stroke-width="11" stroke-linecap="round"><path d="M218 706V680Q218 640 260 640H285"/><path d="M666 640H688Q732 640 732 683V706"/><path d="M218 1064V1087Q218 1129 260 1129H285"/><path d="M666 1129H688Q732 1129 732 1087V1064"/></g></svg>';const n=keep(figma.createNodeFromSvg(svg));for(const ch of n.findAll(()=>true))created.push(ch.id);n.name='Camera target / editable vectors';n.resize(781*scale,1371*scale);place(n,{x:41,y:37});}
}
content.placeholder=false;
}
return {createdNodeIds:created,mutatedNodeIds:mutated,collectionId:collection.id,variables:Object.fromEntries(Object.entries(variables).map(([k,v])=>[k,v.id])),styles:Object.fromEntries(Object.entries(styles).map(([k,v])=>[k,v.id])),masters:Object.fromEntries(Object.entries(masters).map(([k,v])=>[k,v.id])),componentIds:{label:label.id,surface:surface.id},labelKey,images,frames:Object.fromEntries(Object.entries(frames).map(([k,v])=>[k,{id:v.id,width:v.width,height:v.height,textNodes:v.findAllWithCriteria({types:['TEXT']}).length,instances:v.findAllWithCriteria({types:['INSTANCE']}).length}]))};
