// Original individual icon crops; generated by scripts/extract-icon-art.py.
export const sourceArt = {
  "onboarding-recognition": {
    "asset": "icon-onboarding-recognition",
    "x": 102,
    "y": 1127,
    "w": 108,
    "h": 109
  },
  "onboarding-personalized": {
    "asset": "icon-onboarding-personalized",
    "x": 102,
    "y": 1285,
    "w": 108,
    "h": 109
  },
  "onboarding-support": {
    "asset": "icon-onboarding-support",
    "x": 102,
    "y": 1444,
    "w": 108,
    "h": 109
  },
  "onboarding-continue": {
    "asset": "icon-onboarding-continue",
    "x": 649,
    "y": 1613,
    "w": 146,
    "h": 142
  },
  "home-scan-camera": {
    "asset": "icon-home-scan-camera",
    "x": 119,
    "y": 766,
    "w": 169,
    "h": 168
  },
  "home-plan-calendar": {
    "asset": "icon-home-plan-calendar",
    "x": 113,
    "y": 1015,
    "w": 54,
    "h": 58
  },
  "home-health-bars": {
    "asset": "icon-home-health-bars",
    "x": 489,
    "y": 1015,
    "w": 53,
    "h": 58
  },
  "home-plan-chevron": {
    "asset": "icon-home-plan-chevron",
    "x": 379,
    "y": 1087,
    "w": 17,
    "h": 29
  },
  "home-health-chevron": {
    "asset": "icon-home-health-chevron",
    "x": 747,
    "y": 1087,
    "w": 18,
    "h": 29
  },
  "home-scan-chevron": {
    "asset": "icon-home-scan-chevron",
    "x": 736,
    "y": 833,
    "w": 22,
    "h": 35
  },
  "home-see-all-chevron": {
    "asset": "icon-home-see-all-chevron",
    "x": 750,
    "y": 1260,
    "w": 15,
    "h": 24
  },
  "home-nav-home": {
    "asset": "icon-home-nav-home",
    "x": 112,
    "y": 1649,
    "w": 44,
    "h": 47
  },
  "home-nav-plan": {
    "asset": "icon-home-nav-plan",
    "x": 260,
    "y": 1650,
    "w": 41,
    "h": 47
  },
  "home-nav-health": {
    "asset": "icon-home-nav-health",
    "x": 560,
    "y": 1650,
    "w": 51,
    "h": 49
  },
  "home-nav-profile": {
    "asset": "icon-home-nav-profile",
    "x": 710,
    "y": 1650,
    "w": 43,
    "h": 49
  },
  "home-nav-camera": {
    "asset": "icon-home-nav-camera",
    "x": 353,
    "y": 1586,
    "w": 157,
    "h": 153
  },
  "scan-close": {
    "asset": "icon-scan-close",
    "x": 79,
    "y": 169,
    "w": 98,
    "h": 98
  },
  "scan-flash": {
    "asset": "icon-scan-flash",
    "x": 690,
    "y": 168,
    "w": 98,
    "h": 99
  },
  "scan-confirmation": {
    "asset": "icon-scan-confirmation",
    "x": 300,
    "y": 460,
    "w": 63,
    "h": 62
  },
  "scan-instruction-target": {
    "asset": "icon-scan-instruction-target",
    "x": 241,
    "y": 1278,
    "w": 50,
    "h": 53
  },
  "scan-shutter": {
    "asset": "icon-scan-shutter",
    "x": 347,
    "y": 1442,
    "w": 166,
    "h": 165
  },
  "log-back": {
    "asset": "icon-log-back",
    "x": 99,
    "y": 252,
    "w": 25,
    "h": 40
  },
  "log-info": {
    "asset": "icon-log-info",
    "x": 705,
    "y": 405,
    "w": 47,
    "h": 46
  },
  "log-minus": {
    "asset": "icon-log-minus",
    "x": 91,
    "y": 887,
    "w": 78,
    "h": 78
  },
  "log-plus": {
    "asset": "icon-log-plus",
    "x": 297,
    "y": 887,
    "w": 79,
    "h": 78
  },
  "log-estimate-apple": {
    "asset": "icon-log-estimate-apple",
    "x": 115,
    "y": 1052,
    "w": 38,
    "h": 42
  },
  "weekly-back": {
    "asset": "icon-weekly-back",
    "x": 94,
    "y": 285,
    "w": 36,
    "h": 35
  },
  "weekly-calendar": {
    "asset": "icon-weekly-calendar",
    "x": 717,
    "y": 281,
    "w": 47,
    "h": 48
  },
  "weekly-accept": {
    "asset": "icon-weekly-accept",
    "x": 163,
    "y": 1149,
    "w": 38,
    "h": 29
  },
  "weekly-substitute": {
    "asset": "icon-weekly-substitute",
    "x": 439,
    "y": 1148,
    "w": 36,
    "h": 36
  },
  "weekly-more": {
    "asset": "icon-weekly-more",
    "x": 705,
    "y": 1157,
    "w": 35,
    "h": 17
  },
  "weekly-feedback": {
    "asset": "icon-weekly-feedback",
    "x": 126,
    "y": 1252,
    "w": 38,
    "h": 38
  },
  "profile-back": {
    "asset": "icon-profile-back",
    "x": 89,
    "y": 291,
    "w": 27,
    "h": 40
  },
  "profile-account-chevron": {
    "asset": "icon-profile-account-chevron",
    "x": 735,
    "y": 440,
    "w": 20,
    "h": 34
  },
  "profile-dietary": {
    "asset": "icon-profile-dietary",
    "x": 102,
    "y": 586,
    "w": 41,
    "h": 42
  },
  "profile-allergens": {
    "asset": "icon-profile-allergens",
    "x": 102,
    "y": 676,
    "w": 41,
    "h": 42
  },
  "profile-activity": {
    "asset": "icon-profile-activity",
    "x": 102,
    "y": 764,
    "w": 42,
    "h": 50
  },
  "profile-mobility": {
    "asset": "icon-profile-mobility",
    "x": 103,
    "y": 858,
    "w": 41,
    "h": 47
  },
  "profile-glucose": {
    "asset": "icon-profile-glucose",
    "x": 105,
    "y": 952,
    "w": 35,
    "h": 43
  },
  "profile-timezone": {
    "asset": "icon-profile-timezone",
    "x": 102,
    "y": 1040,
    "w": 42,
    "h": 42
  },
  "profile-health": {
    "asset": "icon-profile-health",
    "x": 95,
    "y": 1154,
    "w": 68,
    "h": 69
  },
  "profile-connected": {
    "asset": "icon-profile-connected",
    "x": 598,
    "y": 1175,
    "w": 22,
    "h": 21
  },
  "profile-privacy": {
    "asset": "icon-profile-privacy",
    "x": 105,
    "y": 1318,
    "w": 40,
    "h": 45
  },
  "profile-privacy-chevron": {
    "asset": "icon-profile-privacy-chevron",
    "x": 738,
    "y": 1325,
    "w": 19,
    "h": 31
  }
} as const;
export type SourceArtName = keyof typeof sourceArt;
